extends Node

enum STATES {IDLE, WALK, RUN}
enum GROUP_NAME {DIALOGUE_ACTIONABLES}
enum NPCS {DIANA, FESTUS, LORD_HENRY,GIDEON, RACHAEL, MAID_BOT, DEAD_NPC}

# CHECKPOINT STATES
enum CHECKPOINTS {ONE} ## For all 3 Days
enum CHECKPOINT_ONE {JUST_HEARD_SCREAM, SCREAM_INVESTIGATION_SCENE, INVESTIGATE_DEAD_BODY, MAIDBOT_FINDS_YOU_IN_STORAGE}
